apiVersion: v1
data:
  to.json: |2

    {
      "request": {
        "method": "GET",
        "url": "/hello"
      },
      "response": {
        "status": 503,
        "fixedDelayMilliseconds": 60000
     }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: timeout-backend-cm
